### ISSUE TITLE
Update documentation for configuring Vamp

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#681]
- [x] backend server IP https://github.com/magneticio/vamp/issues/676
- [x] custom HAProxy template https://github.com/magneticio/vamp/issues/675
- [x] HAProxy IP and port for virtual hosts https://github.com/magneticio/vamp/issues/674
- [x] overriding configuration with environment variables https://github.com/magneticio/vamp/issues/670
- [x] virtual host format https://github.com/magneticio/vamp/issues/689
