### ISSUE TITLE
Update docs for DSL and API changes

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#697]
- [x] "routing" -> "gateways", https://github.com/magneticio/vamp/issues/692
- [x] event API get, https://github.com/magneticio/vamp/issues/691
- [x] pattern matching breed dependency, https://github.com/magneticio/vamp/issues/519
- [x] condition instead of filter, https://github.com/magneticio/vamp/issues/476
- [x] metrics endpoint, https://github.com/magneticio/vamp/issues/528
- [x] health endpoint, https://github.com/magneticio/vamp/issues/527
